"""Section 2.3 / Layer-2 training pipeline -- the four-phase
'Expert-Merge-Distill' recipe with separate Box and Point experts.

Source: Layer-2 Section 2.3 of the Visual Primitives release
[@DeepSeekVisualPrimitives], cross-validated by [@CSDNDeepRead].
"""

from gaia.lang import claim, setting

# ---------------------------------------------------------------------------
# Setup: notational conventions for the experts and the unified model
# ---------------------------------------------------------------------------

setup_expert_notation = setting(
    "**Expert notation.** $F_{\\text{TwG}}$ denotes the Box "
    "expert (Thinking with Grounding boxes), $F_{\\text{TwP}}$ "
    "denotes the Point expert (Thinking with Points), and $F$ "
    "denotes the unified model produced at the end of the "
    "pipeline.",
    title="Setup: notation F_TwG (Box expert), F_TwP (Point expert), F (unified)",
)

setup_pattern_conflict = setting(
    "**Pattern-conflict observation.** When `<|box|>` and "
    "`<|point|>` tokens are jointly trained from scratch in a "
    "single model, the two emission patterns interfere -- the "
    "model exhibits trigger-activation collisions, e.g. emitting "
    "boxes when only points are appropriate and vice versa. "
    "Separate per-primitive training avoids this conflict.",
    title="Setup: pattern conflict between joint Box / Point training",
)

# ---------------------------------------------------------------------------
# The four phases as atomic claims
# ---------------------------------------------------------------------------

claim_phase1_separate_experts = claim(
    "**Phase 1 -- separate Box and Point experts.** Two specialized "
    "experts are trained independently: $F_{\\text{TwG}}$ on box-"
    "primitive cold-start data and $F_{\\text{TwP}}$ on point-"
    "primitive cold-start data. Separating them avoids the pattern "
    "conflict that arises when the two primitives are jointly "
    "trained, and lets each expert specialize its trigger-emission "
    "behaviour to its own primitive class.",
    title="Phase 1: train Box expert (F_TwG) and Point expert (F_TwP) separately",
)

claim_phase2_per_expert_grpo = claim(
    "**Phase 2 -- per-expert GRPO RL with the 3-way Reward Model.** "
    "Each expert is fine-tuned via Group Relative Policy "
    "Optimization (GRPO [@GRPO]) using the 3-way Reward Model "
    "(Format / Quality / Task-Specific Accuracy). Reinforcement "
    "happens inside each expert's own primitive regime, so reward-"
    "hacking patterns specific to one primitive cannot bleed into "
    "the other.",
    title="Phase 2: per-expert GRPO RL under 3-way Reward Model",
)

claim_phase3_rft = claim(
    "**Phase 3 -- Rejection Fine-Tuning (RFT) using experts as "
    "rollout source.** A larger pool of rollouts is generated by "
    "the trained experts; high-reward trajectories are selected "
    "and used to fine-tune the unified model under supervised "
    "rejection-sampled fine-tuning. This step transfers expert "
    "behaviour into a single weight set without requiring back-"
    "propagation through the reward model.",
    title="Phase 3: RFT (Rejection Fine-Tuning) uses experts to generate rollouts",
)

claim_phase4_distillation = claim(
    "**Phase 4 -- on-policy distillation into unified $F$.** The "
    "unified model $F$ is on-policy distilled from the two experts: "
    "$F$ generates rollouts itself, and per-token soft targets are "
    "produced by the experts (Box expert for box-emission tokens, "
    "Point expert for point-emission tokens). The result is a "
    "single network that handles both primitive classes without "
    "the pattern conflict of joint cold training.",
    title="Phase 4: on-policy distillation into unified model F",
)

# ---------------------------------------------------------------------------
# Whole-pipeline summary claims
# ---------------------------------------------------------------------------

claim_pipeline_motivation = claim(
    "**Pipeline motivation: avoid pattern conflict, then merge.** "
    "The Expert-Merge-Distill recipe trades a single training run "
    "for a four-phase pipeline that **avoids** the pattern conflict "
    "(Phases 1-2 are pre-merge), **transfers** expert behaviour "
    "into a unified model (Phase 3), and **stabilizes** the "
    "merged behaviour (Phase 4). Each phase exists to neutralize "
    "a specific failure mode of joint training.",
    title="Pipeline motivation: separate-then-merge avoids pattern conflict",
)

claim_pipeline_diagram = claim(
    "**Pipeline diagram (Layer-2 Section 2.3, transcribed "
    "verbatim).**\n\n"
    "```\n"
    "Phase 1: train Box Expert (F_TwG) and Point Expert (F_TwP) separately\n"
    "         |  (avoid pattern conflict -- separate training)\n"
    "Phase 2: per-expert GRPO RL with 3-way Reward Model\n"
    "         |\n"
    "Phase 3: RFT (Rejection Fine-Tuning) -- experts generate rollouts\n"
    "         |\n"
    "Phase 4: On-Policy Distillation -- unified model F\n"
    "```",
    title="Pipeline diagram: 4-phase Expert-Merge-Distill",
)

__all__ = [
    "setup_expert_notation",
    "setup_pattern_conflict",
    "claim_phase1_separate_experts",
    "claim_phase2_per_expert_grpo",
    "claim_phase3_rft",
    "claim_phase4_distillation",
    "claim_pipeline_motivation",
    "claim_pipeline_diagram",
]
