"""Section 3.2 + 3.3 (Layer-3 limitations) -- the two named limitations of
the Visual Primitives system.

Source: Layer-3 sections 3.2 'Trigger-word dependency' and 3.3 'Topology
generalization weakness' of the Visual Primitives release
[@DeepSeekVisualPrimitives], cross-validated by [@CSDNDeepRead].
"""

from gaia.lang import claim, setting

# ---------------------------------------------------------------------------
# Setup: what 'trigger-word' and 'topology generalization' mean
# ---------------------------------------------------------------------------

setup_trigger_word_definition = setting(
    "**Definition: trigger word.** A *trigger word* is an "
    "explicit lexical cue in the prompt (e.g. 'point to', "
    "'box around', 'mark') that activates the model's emission "
    "of `<|point|>` / `<|box|>` primitives. A model has fully "
    "internalized visual primitives if it emits primitives "
    "*spontaneously* whenever they would aid reasoning, even in "
    "the absence of trigger words.",
    title="Definition: trigger word = explicit prompt cue that activates primitive emission",
)

setup_topology_generalization = setting(
    "**Definition: topology generalization.** *Topology "
    "generalization* refers to a model's ability to solve maze / "
    "path tasks on graph topologies that differ from the "
    "training distribution -- e.g. mazes generated by a held-out "
    "algorithm, or non-rectangular topologies the model has not "
    "seen.",
    title="Definition: topology generalization = OOD performance across maze / path topologies",
)

# ---------------------------------------------------------------------------
# Limitation 1 -- trigger-word dependency
# ---------------------------------------------------------------------------

claim_lim_trigger_word_dependency = claim(
    "**Limitation 1: trigger-word dependency.** The trained "
    "Visual Primitives model emits `<|point|>` / `<|box|>` "
    "tokens reliably only when the prompt contains an explicit "
    "trigger word ('point to', 'box around', 'mark'). Without "
    "such a cue, the model frequently falls back to natural-"
    "language descriptions of position. This indicates that **"
    "the model has not yet learned WHEN to point** -- the "
    "primitive-emission policy has been internalized only "
    "conditionally on trigger words.",
    title="Limitation 1: trigger-word dependency -- model has not learned WHEN to point",
)

claim_lim_trigger_incomplete_internalization = claim(
    "**Interpretation: trigger dependency = incomplete "
    "internalization of visual primitives.** A fully internalized "
    "policy would invoke primitives whenever they reduce "
    "referential ambiguity, regardless of prompt phrasing. "
    "Trigger dependency means the model has learned 'how to "
    "point when asked' but not 'when pointing helps' -- the "
    "selection policy is still externally specified.",
    title="Interpretation: trigger dependency means primitive-emission policy is externally specified",
)

claim_lim_trigger_analogue_to_armskill = claim(
    "**Literature analogue: trigger dependency parallels the "
    "ARM Execution / Skill modality limit (the agent must be "
    "told *to* invoke a skill, cannot decide on its own *when*). "
    "The pattern -- a learned capability that fires only "
    "conditionally on an explicit cue -- recurs across LLM "
    "systems (e.g. tool-use agents that need explicit tool-"
    "request prompts), suggesting a shared structural cause: "
    "training signal rewards the *correct invocation* but "
    "rarely the *correct timing*.",
    title="Analogue: trigger dependency parallels ARM Execution/Skill 'when-to-invoke' problem",
)

# ---------------------------------------------------------------------------
# Limitation 2 -- topology generalization weakness
# ---------------------------------------------------------------------------

claim_lim_topology_weakness = claim(
    "**Limitation 2: topology generalization weakness.** Maze "
    "performance is strong **in distribution** (rectangular / "
    "circular / hexagonal topologies generated by the training "
    "algorithms) but degrades on out-of-distribution topologies. "
    "The model has learned the maze structures it was trained "
    "on but does not transfer that competence to new graph "
    "topologies as effectively.",
    title="Limitation 2: topology generalization weakness (in-domain strong, OOD weak)",
)

claim_lim_topology_sharpening_tradeoff = claim(
    "**Interpretation: classic RL sharpening-vs-generalization "
    "tradeoff.** Fine-grained, task-specific reward functions "
    "(the per-task accuracy RM, especially the maze "
    "exploration-progress + wall-violation + path-validity "
    "decomposition) sharpen in-distribution performance at the "
    "cost of out-of-distribution generalization. This matches "
    "the well-known reinforcement-learning observation that "
    "more precisely shaped rewards trade generalization for "
    "in-domain peak.",
    title="Interpretation: topology weakness = RL sharpening-vs-generalization tradeoff",
)

# ---------------------------------------------------------------------------
# Both limitations as a synthesis claim
# ---------------------------------------------------------------------------

claim_lim_synthesis_two_open_problems = claim(
    "**Synthesis: two open problems for the Visual Primitives "
    "programme.** (i) *When-to-point*: discovering training "
    "signal that rewards spontaneous, trigger-free primitive "
    "emission. (ii) *Topology-agnostic shaping*: designing "
    "reward functions that retain in-domain sharpness without "
    "sacrificing OOD transfer. Both are limitations of the "
    "current training recipe rather than of the architectural "
    "idea, so progress on either is consistent with the "
    "method's core thesis.",
    title="Synthesis: two open problems (when-to-point + topology-agnostic reward shaping)",
)

__all__ = [
    "setup_trigger_word_definition",
    "setup_topology_generalization",
    "claim_lim_trigger_word_dependency",
    "claim_lim_trigger_incomplete_internalization",
    "claim_lim_trigger_analogue_to_armskill",
    "claim_lim_topology_weakness",
    "claim_lim_topology_sharpening_tradeoff",
    "claim_lim_synthesis_two_open_problems",
]
