"""
Section 3: ARC Methodology — Dual Architecture, Memory Construction, Reflection
================================================================================

Formalizes the ARC framework: dual-component (Actor + Context Manager) architecture,
incremental memory construction, reflection-driven reorganization, the agent execution
loop, and supervised training of the Context Manager.
"""

from gaia.lang import claim, setting, support

from .motivation import (
    active_management_view,
    contribution_arc_framework,
    contribution_dual_architecture,
)

# --- Architectural definitions ---

dual_architecture = setting(
    "ARC adopts a *dual-component architecture* that explicitly separates action execution "
    "from context management. The agent maintains three internal components at each turn:\n\n"
    "- **Checklist** ($L_t$): an inspectable and mutable control structure tracking objectives "
    "and execution progress.\n"
    "- **Interaction Memory** ($M_t$): a dynamically managed memory compactly summarizing "
    "task-relevant information from past interactions.\n"
    "- **Previous Interaction** ($I_{t-1} = (r_{t-1}, a_{t-1}, o_{t-1})$): the complete raw "
    "interaction from the preceding turn — internal reasoning, executed action, and resulting "
    "observation.\n\n"
    "A learnable model called the *Context Manager (CM)* is responsible for context "
    "management; the *Actor* is responsible only for action generation.",
    title="Dual-component architecture (Actor + CM)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.1"},
)

actor_policy = setting(
    "At turn $t$, the Actor generates an internal reasoning state and an action via:\n"
    "$$(r_t, a_t) \\sim \\pi_{actor}(Q, L_{t-1}, M_{t-1}, I_{t-1})$$\n"
    "where $Q$ is the task query. The environment then executes $a_t$ and returns observation $o_t$.",
    title="Actor policy (Eq. 3)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.3, Eq. 3"},
)

incremental_summarization = setting(
    "The Context Manager updates the interaction memory at each turn via incremental summarization:\n"
    "$$M_t = \\mathrm{Summarize}(Q, L_{t-1}, M_{t-1}, I_{t-1})$$\n"
    "This update is *strictly incremental*: the CM incorporates information only from the most "
    "recent interaction and does not revise, reorder, or remove previously stored memory content. "
    "The summarizer removes redundancy while preserving task-relevant evidence and factual fidelity, "
    "without introducing new assumptions.",
    title="Incremental summarization (Eq. 1)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.2.1, Eq. 1"},
)

raw_recent_turn_retained = setting(
    "The most recent turn's interaction is *not* immediately compressed at the time of action "
    "selection. Instead it is retained in raw form and provided directly to the Actor at the next "
    "turn, ensuring access to fine-grained details before being absorbed into the interaction memory.",
    title="Raw recent-turn retention",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.2.1"},
)

reflection_operator = setting(
    "When triggered, the Context Manager performs a joint internal state update via the reflection "
    "operator $R$:\n"
    "$$(M_t, L_t) \\leftarrow R(Q, L_{t-1}, M_t, I_{t-1})$$\n"
    "Reflection enables *non-local* modifications: the CM may rewrite or merge memory elements to "
    "correct errors, remove outdated assumptions, or re-emphasize task-relevant information. The "
    "checklist is revised in the same step. Reflection is purely an internal state transformation; "
    "it does not generate actions or modify the actor's policy.",
    title="Reflection operator (Eq. 2)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.2.2, Eq. 2"},
)

reflection_trigger = setting(
    "Reflection triggering is integrated into the summarization process: during each incremental "
    "update, the CM performs a lightweight self-assessment of the current interaction memory to "
    "detect signals of degradation — stalled progress, unresolved inconsistencies, or ineffective "
    "repetition. The CM decides whether to trigger reflection based on this assessment.",
    title="Reflection trigger (self-assessment)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.2.2"},
)

cm_training_setup = setting(
    "The Context Manager is trained via supervised fine-tuning (SFT) on trajectories collected "
    "from information-seeking and search-based tasks. Each training example pairs an interaction "
    "$I_t$ with target memory and checklist states $(M_t^*, L_t^*)$. Training trajectories are "
    "generated by strong language models and filtered to retain only those exhibiting coherent "
    "summarization and valid reflection behavior. Trained CM (\"ARC-CM\") in Section 4.4 uses "
    "Qwen3-14B as base.",
    title="CM training setup (SFT)",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.4, Appendix A"},
)

# --- Core methodological claims (derived) ---

incremental_preserves_evidence = claim(
    "Always-on incremental summarization preserves complete semantic information from the most "
    "recent interaction *before* any abstraction or omission accumulates across multiple steps, "
    "yielding a compact yet semantically faithful representation of the agent's past experience.",
    title="Incremental summarization preserves evidence",
    metadata={"source": "artifacts/2601.12030.pdf, Sections 3.2.1, 4.5"},
)

reflection_enables_repair = claim(
    "Reflection-driven reorganization enables the agent to repair degraded context: incorrect "
    "early assumptions, outdated information, or misplaced emphasis can be rewritten, merged, or "
    "removed — modifications that incremental summarization alone cannot perform because it never "
    "revises previously stored content.",
    title="Reflection enables non-local context repair",
    metadata={"source": "artifacts/2601.12030.pdf, Section 3.2.2"},
)

decoupling_enables_reuse = claim(
    "Decoupling action execution from context management makes the Context Manager reusable "
    "across different Actors and tasks, and allows context-management performance to be analyzed "
    "and improved independently of Actor capability.",
    title="Decoupling enables CM reuse and isolated analysis",
    metadata={"source": "artifacts/2601.12030.pdf, Sections 3.1, 4.4, 5"},
)

# --- Strategies linking design to motivation ---

strat_arc_framework = support(
    [incremental_preserves_evidence, reflection_enables_repair],
    contribution_arc_framework,
    background=[dual_architecture, incremental_summarization, reflection_operator],
    reason=(
        "The ARC framework (@contribution_arc_framework) is constituted by exactly two mechanisms: "
        "always-on incremental summarization (@incremental_summarization), which preserves evidence "
        "(@incremental_preserves_evidence), and selectively-triggered reflection "
        "(@reflection_operator), which enables non-local repair (@reflection_enables_repair). "
        "Together these realize the active-management view by continuously updating the working "
        "context within the dual-component architecture (@dual_architecture)."
    ),
    prior=0.9,
)

strat_dual_architecture = support(
    [decoupling_enables_reuse],
    contribution_dual_architecture,
    background=[dual_architecture, actor_policy, cm_training_setup],
    reason=(
        "The dual-component architecture (@dual_architecture) is well-defined: the Actor is "
        "responsible for $(r_t, a_t)$ given current context (@actor_policy), and the Context "
        "Manager performs only memory/checklist updates. Because the CM is a separate trainable "
        "component (@cm_training_setup), it can be paired with any Actor and reused across tasks "
        "(@decoupling_enables_reuse), substantiating the dual-architecture contribution."
    ),
    prior=0.9,
)

__all__ = [
    "dual_architecture",
    "actor_policy",
    "incremental_summarization",
    "raw_recent_turn_retained",
    "reflection_operator",
    "reflection_trigger",
    "cm_training_setup",
    "incremental_preserves_evidence",
    "reflection_enables_repair",
    "decoupling_enables_reuse",
    "strat_arc_framework",
    "strat_dual_architecture",
]
