"""Section 4: Learning to Recur as a Whole -- inner-outer loop training
algorithm and gradient-stability analysis (Theorem 4.1).

Source: Yang et al. 2026 [@Yang2026RecursiveMAS], Section 4 + Appendix A.2-A.3.
"""

from gaia.lang import claim, setting

# ---------------------------------------------------------------------------
# Section 4: training paradigm overview
# ---------------------------------------------------------------------------

setup_two_stage_training = setting(
    "**Two-stage training paradigm.** The recursive learning algorithm "
    "trains *only* the RecursiveLink modules, leaving every base LLM's "
    "parameters frozen. Training proceeds in two stages: (i) a "
    "preliminary **inner loop** that warm-starts each agent's inner "
    "RecursiveLink in parallel for stronger latent thoughts generation, "
    "and (ii) an iterative **outer loop** that progressively co-"
    "optimizes the outer RecursiveLinks across the entire system "
    "over recursion rounds.",
    title="Setup: 2-stage training -- inner loop (per-agent warm-up) + outer loop (system-level recursion)",
    metadata={
        "figure": "artifacts/2604.25917.pdf, Fig. 4",
        "caption": "Fig. 4: Two-stage training pipeline of RecursiveMAS -- parallel inner-loop training, then recursive outer-loop training over n rounds.",
    },
)

# ---------------------------------------------------------------------------
# Section 4.1: model-level inner-loop training
# ---------------------------------------------------------------------------

setup_inner_loop_objective = setting(
    "**Inner-loop training objective (Eq. 5).** For each agent $A_i$ "
    "with parameters $\\theta_i$ and a training example "
    "$(x, y) \\in \\mathcal{D}_{train}$, the target latent thoughts "
    "distribution is constructed by passing the ground-truth text $y$ "
    "through agent $A_i$'s standard input embedding layer "
    "$\\mathrm{Emb}_{\\theta_i}$. The inner link "
    "$\\mathcal{R}_{in}$ is then trained with the cosine-similarity "
    "regression loss\n"
    "$$\\mathcal{L}_{in} = 1 - \\cos\\bigl(\\mathcal{R}_{in}(H), "
    "\\mathrm{Emb}_{\\theta_i}(y)\\bigr),$$\n"
    "where $H$ denotes the last-layer latent thoughts generated by "
    "$A_i$. The objective encourages each agent to leverage its inner "
    "link to *align latent thoughts with the input-embedding "
    "semantic distribution*, eliminating explicit decoding and "
    "re-encoding.",
    title="Setup: L_in = 1 - cos(R_in(H), Emb_{theta_i}(y)) (Eq. 5)",
)

claim_inner_loop_warm_start = claim(
    "**Inner-loop training warm-starts the agents for latent thoughts "
    "generation.** Off-the-shelf text-generation LLMs are not "
    "natively distributed over their own *input embedding* space "
    "during generation. By minimizing $\\mathcal{L}_{in}$, the inner "
    "RecursiveLink learns to map last-layer hidden states back to a "
    "distribution close to the input-embedding distribution of the "
    "ground-truth answer. This per-agent inner training is run in "
    "parallel across all agents and provides a model-level warm "
    "start before the outer recursive loop begins.",
    title="Claim: parallel inner-loop training warm-starts each agent for latent thoughts generation",
)

# ---------------------------------------------------------------------------
# Section 4.2: system-level outer-loop training
# ---------------------------------------------------------------------------

setup_outer_loop_objective = setting(
    "**Outer-loop training objective (Eq. 6).** Let $\\mathcal{S}^{(r)}$ "
    "denote the system state at recursion round $r = 1, \\dots, n$. "
    "During outer-loop training, the system is unrolled along its "
    "looped structure for $n$ forward rounds. After the final textual "
    "prediction is produced in the last recursion round, all outer "
    "RecursiveLinks are jointly optimized with the cross-entropy "
    "objective\n"
    "$$\\mathcal{L}_{out} = \\mathrm{CE}\\bigl(\\mathcal{S}^{(n)} "
    "(\\mathcal{S}^{(n-1)}(\\cdots \\mathcal{S}^{(1)}(x))), y\\bigr).$$\n"
    "The full computation graph is preserved along the recursive "
    "paths so that gradient back-propagation assigns each outer link "
    "a *shared credit signal* according to its global contribution "
    "to the final prediction.",
    title="Setup: L_out = CE(S^(n) o S^(n-1) o ... o S^(1)(x), y) -- joint cross-entropy over n recursion rounds (Eq. 6)",
)

claim_shared_credit_assignment = claim(
    "**Shared gradient-based credit assignment across recursion "
    "rounds.** Because the outer-loop loss back-propagates through "
    "the entire $n$-round recursion graph with all outer links "
    "shared across rounds, every outer link receives gradient signal "
    "proportional to its global contribution to the final answer. "
    "This exposes each agent to feedback from itself and from the "
    "other agents in *previous rounds*, enabling iterative refinement "
    "of collaboration as one unified system rather than as a chain "
    "of independent fine-tunes.",
    title="Claim: outer-loop training implements shared gradient credit assignment across recursion rounds",
)

claim_inference_matches_training_rounds = claim(
    "**Inference uses the same number of recursion rounds as training.** "
    "During inference, RecursiveMAS performs recursive generation by "
    "following the same $n$ recursion rounds as in the outer-loop "
    "training stage, rather than dynamically choosing the number of "
    "rounds. Inference recursion depth is therefore a hyperparameter "
    "matched to training-time depth and is studied as a scaling axis "
    "in Section 5.1.",
    title="Claim: inference recursion depth = training recursion depth (no dynamic stopping)",
)

# ---------------------------------------------------------------------------
# Theorem 4.1: gradient stability
# ---------------------------------------------------------------------------

setup_realistic_assumptions = setting(
    "**Realistic Assumptions (Appendix A.2).** Text-based supervised "
    "fine-tuning during recursion can be regarded as using "
    "$\\mathcal{R}_{text}(h) = W_{in} \\, \\mathrm{softmax}(W_{out} h)$ "
    "as the recursive link, where $W_{in}$ is the token-to-embedding "
    "matrix and $W_{out}$ is the embedding-to-logits matrix. The "
    "analysis assumes $\\|W_{in}\\|_2 \\le O(1)$ and "
    "$\\|W_{out}\\|_2 \\le O(1)$. For RecursiveLink "
    "$\\mathcal{R}(h)$, we assume $W_1, W_2$ follow Kaiming-normal "
    "initialization, and we only analyze the case where $W_3 = I$ "
    "(identity, i.e., the inner-link case).",
    title="Setup: Realistic Assumptions for Theorem 4.1 (R_text via softmax+W_in; R via Kaiming-init MLP, W_3 = I)",
)

setup_confidence_assumption = setting(
    "**Token-confidence assumption.** Theorem 4.1 conditions on tokens "
    "being **confident**, i.e., the per-step entropy of the next-token "
    "distribution $p = \\mathrm{softmax}(W_{out} h)$ satisfies "
    "$H(p) \\le \\epsilon$ for some $\\epsilon \\ll 1$. This regime "
    "is typical of post-SFT models on confident generation steps.",
    title="Setup: confidence assumption -- next-token entropy <= epsilon << 1",
)

claim_jacobian_text = claim(
    "**Jacobian of the text-based recursive link.** Applying the "
    "chain rule to $\\mathcal{R}_{text}(h) = W_{in} \\, "
    "\\mathrm{softmax}(W_{out} h)$ yields\n"
    "$$J_{text} = \\frac{\\partial \\mathcal{R}_{text}(h)}{\\partial h} "
    "= W_{in} S \\, W_{out}, \\quad S = \\mathrm{diag}(p) - p p^T,$$\n"
    "where $S$ is the covariance matrix of the categorical "
    "distribution $p$. By sub-multiplicativity, "
    "$\\|J_{text}\\|_2 \\le O(\\|S\\|_2)$, and because "
    "$\\|S\\|_2 \\le \\mathrm{Tr}(S) = 1 - \\|p\\|_2^2 \\le \\epsilon$ "
    "(via $\\ln z \\le z - 1$ applied to the entropy bound), one "
    "obtains $\\|\\partial \\mathcal{R}_{text}(h)/\\partial h\\|_2 "
    "\\le O(\\epsilon)$.",
    title="Lemma: ||d R_text(h)/d h||_2 <= O(epsilon) under confident-token assumption",
)

claim_jacobian_recursive_link = claim(
    "**Jacobian of the RecursiveLink.** Applying the chain rule to "
    "$\\mathcal{R}(h) = h + W_2 \\sigma(W_1 h)$ yields\n"
    "$$J = \\frac{\\partial \\mathcal{R}(h)}{\\partial h} = I + "
    "W_2 \\Sigma' W_1, \\quad \\Sigma' = \\mathrm{diag}(\\sigma'(W_1 h)).$$\n"
    "By the triangle inequality, "
    "$|\\,\\|J\\|_2 - 1\\,| \\le \\|J - I\\|_2 = \\|W_2 \\Sigma' W_1\\|_2$. "
    "Since $W_1, W_2$ are Kaiming-initialized and $|\\sigma'| \\le O(1)$, "
    "by the sub-Gaussian matrix concentration inequality, with "
    "probability $\\ge 1 - \\delta$, "
    "$\\|W_2 \\Sigma' W_1\\|_2 \\le O\\bigl(\\sqrt{(1/d_h) \\log(1/"
    "\\delta)} + 1\\bigr)$, giving "
    "$\\|J\\|_2 \\ge \\Omega\\bigl(1 - \\sqrt{(1/d_h) \\log(1/"
    "\\delta)}\\bigr)$.",
    title="Lemma: ||d R(h)/d h||_2 >= Omega(1 - sqrt((1/d_h) log(1/delta))) w.p. >= 1-delta",
)

claim_theorem_4_1 = claim(
    "**Theorem 4.1 (Gradient Stability).** Under the Realistic "
    "Assumptions (Appendix A.2), if tokens are confident with "
    "entropy $\\le \\epsilon$ (typically $\\epsilon \\ll 1$), then "
    "directly applying text-based SFT during recursion (recursive "
    "link $\\mathcal{R}_{text}(h)$) suffers **gradient vanishing** "
    "(gradient norm close to 0), while RecursiveMAS with the "
    "RecursiveLink $\\mathcal{R}$ maintains **stable, near-constant "
    "gradients** (norm close to 1) during looped back-propagation. "
    "Formally, with probability $\\ge 1 - \\delta$,\n"
    "$$\\Bigl\\|\\frac{\\partial \\mathcal{R}_{text}(h)}{\\partial h}"
    "\\Bigr\\|_2 \\le O(\\epsilon) \\ll 1, \\qquad "
    "\\Bigl\\|\\frac{\\partial \\mathcal{R}(h)}{\\partial h}"
    "\\Bigr\\|_2 \\ge \\Omega\\Bigl(1 - \\sqrt{(1/d_h) \\log(1/"
    "\\delta)}\\Bigr).$$",
    title="Theorem 4.1: text-based SFT suffers gradient vanishing; RecursiveMAS keeps gradient norm near 1",
    metadata={
        "figure": "artifacts/2604.25917.pdf, Section 4 + Appendix A.3",
    },
)

claim_theory_motivates_latent = claim(
    "**The two theoretical results jointly motivate latent over text "
    "interaction.** Proposition 3.1 (lower runtime complexity in "
    "latent space) and Theorem 4.1 (stable gradient norm during "
    "recursive back-propagation) make the case that whole-system "
    "co-optimization of RecursiveMAS is both *easier* (no gradient "
    "vanishing across recursion rounds) and *more efficient* (no "
    "$|V|$-scale decoding per intermediate step) than its text-"
    "mediated alternative.",
    title="Synthesis: Prop. 3.1 (efficiency) + Thm. 4.1 (gradient stability) jointly justify latent-only intermediate recursion",
)

__all__ = [
    "setup_two_stage_training",
    "setup_inner_loop_objective",
    "claim_inner_loop_warm_start",
    "setup_outer_loop_objective",
    "claim_shared_credit_assignment",
    "claim_inference_matches_training_rounds",
    "setup_realistic_assumptions",
    "setup_confidence_assumption",
    "claim_jacobian_text",
    "claim_jacobian_recursive_link",
    "claim_theorem_4_1",
    "claim_theory_motivates_latent",
]
