"""Introduction: Metacognitive Control and Confidence-Driven Abstention in LLMs"""

from gaia.lang import claim, setting, question

# ── Established background ──────────────────────────────────────────────────

metacognition_biology = setting(
    "Metacognition—the ability to reflect on and assess the quality of one's own "
    "cognitive performance—has been documented across diverse animal species, including "
    "rats, primates, and humans [@KepecsMainen2012].",
    title="Metacognition in biological systems",
)

confidence_definition = setting(
    "Confidence is defined as an internal estimate of the probability that a decision "
    "is correct. It serves as a key metacognitive signal that guides adaptive behavior "
    "(e.g., deciding whether to change one's mind or gather more information) "
    "[@KepecsMainen2012; @Pouget2016].",
    title="Definition of confidence as metacognitive signal",
)

two_stage_framework = setting(
    "The two-stage confidence-decision framework, drawn from human neuroscience and "
    "psychophysics [@FlemingDaw2017; @KepecsMainen2012], posits: "
    "Stage 1 — confidence representations are formed as a latent internal variable "
    "from evidence accumulation; "
    "Stage 2 — a threshold-based policy σ((T − C) / τ) maps confidence C against "
    "threshold T (with policy temperature τ) to produce a binary behavioral decision "
    "(e.g., answer vs. abstain). "
    "This framework operates at a computational level of analysis without prescribing "
    "specific neural or algorithmic implementation.",
    title="Two-stage confidence-decision framework",
)

abstention_paradigm_design = setting(
    "The four-phase abstention paradigm is designed as follows: "
    "Phase 1 — model answers 4-way multiple-choice questions with no abstention option, "
    "yielding Phase 1 Chosen Confidence (calibrated logit confidence in the chosen option) "
    "uncontaminated by an abstention decision; "
    "Phase 2 — same questions with a 5th abstention option ('choose 5 if no clearly correct answer'); "
    "Phase 3 — same Phase 2 prompt with activation steering applied at inference time; "
    "Phase 4 — model first rates its confidence (0–100%), then answers only if confidence exceeds "
    "an instructed threshold T varied from 0% to 100% in 10% increments. "
    "Phase 1 Chosen Confidence is used as the predictor in Phases 2 and 4 because it is "
    "pre-decisional and uncontaminated.",
    title="Four-phase abstention paradigm design",
)

dataset_setting = setting(
    "The SimpleQA dataset [@Wei2024] is a challenging factuality dataset of ~4,000 questions. "
    "Questions were converted to 4-way multiple-choice format with one correct answer, one similar "
    "foil, one dissimilar foil, and one unrelated foil, generated by prompting Gemma 3 12B. "
    "A separate set of 1,000 questions was used for calibration; another 1,000 for main experiments. "
    "All questions were objectively answerable.",
    title="Dataset: SimpleQA 4-way multiple-choice",
)

calibration_method = setting(
    "Temperature scaling [@Guo2017] is used to calibrate model confidence: logits z are divided "
    "by a learned scaling temperature τ_scale before softmax, minimizing Expected Calibration Error (ECE) "
    "on 1,000 held-out calibration questions. AUROC (area under the receiver operating characteristic) "
    "measures discrimination between correct and incorrect predictions independently of calibration.",
    title="Calibration method: temperature scaling",
)

# ── Research questions ───────────────────────────────────────────────────────

q_metacognitive_use = question(
    "Do LLMs actually use internal confidence signals to control their own behavior "
    "(specifically abstention decisions), rather than merely being able to produce "
    "confidence ratings when asked?"
)

q_causal_role = question(
    "Is the role of confidence in driving abstention causal (not merely correlational)?"
)

q_two_stage = question(
    "Can LLM abstention behavior be characterized by a two-stage framework consisting of "
    "Stage 1 confidence representations and a Stage 2 threshold-based policy?"
)

# ── Prior-work gap claim ─────────────────────────────────────────────────────

gap_prior_work = claim(
    "Prior work on LLM abstention has largely relied on post-hoc thresholding or specialized "
    "fine-tuning [@Tjandra2024; @Yadkori2024; @Chuang2024; @Zhang2024], and does not examine "
    "whether LLMs natively use internal confidence signals to guide abstention. "
    "Clear causal evidence that LLMs exploit their internal sense of confidence for abstention "
    "decisions has been lacking.",
    title="Gap in prior work on native confidence-driven abstention",
    background=[metacognition_biology, confidence_definition],
)

llm_calibration_prior = claim(
    "A substantial body of research demonstrates that confidence signals can be extracted "
    "from LLM outputs and calibrated using methods such as temperature scaling "
    "[@Xiong2023; @Steyvers2025; @Guo2017]. "
    "However, whether models internally use these signals to guide their own decisions "
    "remains largely unexplored.",
    title="LLM confidence calibration established but usage unknown",
    background=[calibration_method],
)
