"""Section 4.3: Ablation Studies"""

from gaia.lang import claim, setting, support, induction, complement

from .s3_mce_framework import agentic_crossover_claim, skill_unifies_levels
from .s4_experiments import (
    mce_offline_gains,
    mce_efficiency_mechanism,
    mce_training_efficiency,
)

# ── Settings ──────────────────────────────────────────────────────────────────

setup_ablation_finer = setting(
    "Ablation experiments conducted on FiNER benchmark. "
    "Three MCE variants compared: (1) MCE w/o skills — base-agent operates without skill guidance; "
    "(2) MCE w/ fixed skill — base-agent follows a single skill generated by meta-agent from task specs, "
    "without iterative evolution; (3) MCE full — complete MCE with evolving skills.",
    title="Ablation study setup on FiNER",
)

# ── Claims ────────────────────────────────────────────────────────────────────

ablation_bilevel_boost = claim(
    "In the offline setting on FiNER, full MCE (evolving skills) achieves 75% accuracy versus "
    "73% for MCE without skills. Meta-level skill evolution provides a statistically clear "
    "performance boost of 2 percentage points.",
    title="Meta-level skill evolution adds performance boost",
    metadata={"source_table": "artifacts/2601.21557.pdf, Table 3"},
)

ablation_agentic_base = claim(
    "Even without skill guidance, the MCE base-agent alone outperforms ACE in both offline "
    "and online settings (73% vs 71% offline; 67% vs 64% online on FiNER). "
    "This indicates that fully agentic context engineering can be effective without manual scaffolding.",
    title="Agentic base-agent outperforms ACE without skill guidance",
    metadata={"source_table": "artifacts/2601.21557.pdf, Table 3"},
)

ablation_fixed_skill_variance = claim(
    "MCE with a fixed (non-evolving) skill shows high variance across tasks, achieving 71% on FiNER "
    "offline (matching ACE) and variable performance on other benchmarks. "
    "Fixed skill quality depends solely on task specification without feedback from validation performance.",
    title="Fixed skill has high variance without iterative evolution",
    metadata={"source_table": "artifacts/2601.21557.pdf, Table 3"},
)

bilevel_design_validated = claim(
    "The full bi-level MCE design with iterative skill evolution is validated as necessary for "
    "consistent performance gains: each component (agentic base, fixed skill, evolving skill) "
    "adds incremental value, and the complete system achieves the best offline performance (75% FiNER).",
    title="Bi-level MCE design validated by ablation",
)

strat_bilevel_necessary = support(
    [ablation_bilevel_boost, ablation_agentic_base, ablation_fixed_skill_variance],
    bilevel_design_validated,
    reason=(
        "The three-way comparison shows: (1) meta-level evolution adds a clear boost over skill-less "
        "(@ablation_bilevel_boost — 75% vs 73%), (2) the base-agent alone already exceeds fixed-harness methods "
        "(@ablation_agentic_base — 73% vs 71% offline), and (3) a single static skill lacks the adaptability "
        "gained by iterative validation feedback (@ablation_fixed_skill_variance — high task variance). "
        "Together, these validate that the full bi-level design is necessary for consistent gains."
    ),
    prior=0.85,
)

# ── Model confound ruling out ─────────────────────────────────────────────────

minimax_degrades_ace = claim(
    "Replacing the reflector and curator in ACE with MiniMax M2.1 (MCE's agentic model) "
    "degrades ACE's performance: MiniMax M2.1 in ACE generates more verbose playbooks "
    "(114K tokens vs 79K tokens at completion) but achieves lower final accuracy (67% vs 70%) on FiNER.",
    title="MiniMax M2.1 degrades ACE performance",
    metadata={"source_table": "artifacts/2601.21557.pdf, Table 4"},
)

model_confound_ruled_out = claim(
    "MCE's performance gains are attributable to the MCE framework design, not to superior "
    "capabilities of MiniMax M2.1 (the agentic model). The gains are demonstrated to be "
    "framework-specific, not model-specific.",
    title="Model confound ruled out for MCE gains",
)

strat_confound_ruled = support(
    [minimax_degrades_ace],
    model_confound_ruled_out,
    reason=(
        "If MCE's gains were due to MiniMax M2.1's superior capabilities, then using MiniMax M2.1 "
        "within ACE should also improve ACE. Instead, @minimax_degrades_ace shows that "
        "MiniMax M2.1 degrades ACE performance (67% vs 70%), ruling out model capability transfer "
        "as the source of MCE's advantage."
    ),
    prior=0.92,
)

# Complement: either framework or model drives MCE gains
alt_model_capability = claim(
    "MCE's performance gains are primarily attributable to MiniMax M2.1's superior capabilities "
    "rather than the MCE bi-level framework design.",
    title="Alternative: MCE gains due to MiniMax M2.1 model capability",
)

either_framework_or_model = complement(
    model_confound_ruled_out,
    alt_model_capability,
    reason=(
        "Either the gains come from the MCE framework design or from MiniMax M2.1's model capabilities — "
        "these are the two exhaustive explanations for why MCE outperforms ACE."
    ),
    prior=0.95,
)

# ── Induction: multi-benchmark confirmation of MCE's superiority ──────────────

mce_law = claim(
    "MCE's bi-level skill evolution consistently produces superior context optimization outcomes "
    "compared to fixed-harness CE methods across diverse NLP task domains.",
    title="MCE law: consistent superiority across domains",
)

obs_finer = claim(
    "MCE achieves 75% accuracy on FiNER (financial NER), surpassing ACE (71%) and all baselines.",
    title="FiNER: MCE outperforms all baselines",
)

obs_uspto = claim(
    "MCE achieves 20% accuracy on USPTO-50k (retrosynthesis prediction), surpassing ACE (18%).",
    title="USPTO-50k: MCE outperforms ACE",
)

obs_s2d = claim(
    "MCE achieves 89.2% accuracy on Symptom2Disease (medical diagnosis), surpassing ACE (79.2%).",
    title="Symptom2Disease: MCE outperforms ACE",
)

obs_law = claim(
    "MCE achieves 0.70 micro-F1 on LawBench (legal charge prediction), matching or surpassing "
    "ACE (0.65) despite the task requiring detailed legal domain knowledge.",
    title="LawBench: MCE matches/surpasses ACE",
)

obs_aegis = claim(
    "MCE achieves 0.80 F1 on AEGIS2 (AI safety classification), surpassing ACE (0.68).",
    title="AEGIS2: MCE outperforms ACE",
)

s_finer = support(
    [mce_law], obs_finer,
    reason="MCE law predicts FiNER superiority; confirmed by empirical measurement",
    prior=0.88,
)
s_uspto = support(
    [mce_law], obs_uspto,
    reason="MCE law predicts USPTO-50k superiority; confirmed by empirical measurement",
    prior=0.80,
)
s_s2d = support(
    [mce_law], obs_s2d,
    reason="MCE law predicts Symptom2Disease superiority; confirmed by large margin",
    prior=0.90,
)
s_law = support(
    [mce_law], obs_law,
    reason="MCE law predicts LawBench superiority; confirmed by F1 comparison",
    prior=0.82,
)
s_aegis = support(
    [mce_law], obs_aegis,
    reason="MCE law predicts AEGIS2 superiority; confirmed despite safety-specific challenge",
    prior=0.85,
)

ind_12 = induction(s_finer, s_uspto, law=mce_law,
    reason="FiNER (financial NER) and USPTO-50k (chemistry retrosynthesis) are independent domains")
ind_123 = induction(ind_12, s_s2d, law=mce_law,
    reason="Symptom2Disease (medical) is independent of financial and chemistry tasks")
ind_1234 = induction(ind_123, s_law, law=mce_law,
    reason="LawBench (Chinese legal) is independent of all prior domains")
ind_all = induction(ind_1234, s_aegis, law=mce_law,
    reason="AEGIS2 (AI safety classification) is independent of the prior four domains")
