"""Section 3: Methodology — The Conditional Information Bottleneck Framework"""

from gaia.lang import claim, setting, support, deduction

from .motivation import (
    ib_markov_def,
    transformer_attention_def,
    cot_cost_problem,
    budget_forcing_heuristic,
    q_principled_compression,
)
from .s2_background import grpo_def

# --- Settings: mathematical framework ---

cib_objective_def = setting(
    "The Conditional Information Bottleneck (CIB) objective for reasoning trace optimization is: "
    "$$\\mathcal{L}_{\\text{CIB}}(\\theta) = I(Z;Y|X) - \\beta I(X;Z)$$\n"
    "where X is the input prompt, Z is the reasoning trace generated by policy $\\pi_\\theta$, "
    "Y is the correct answer, $\\beta > 0$ is the compression trade-off parameter, "
    "$I(Z;Y|X)$ is the conditional mutual information (sufficiency/accuracy term), "
    "and $I(X;Z)$ is the mutual information between prompt and trace (minimality/compression term).",
    title="CIB objective definition",
)

variational_sufficiency_def = setting(
    "The variational lower bound for the sufficiency term $I(Z;Y|X)$ is derived using an "
    "auxiliary verifier distribution $Q_\\rho(y|x,z)$:\n"
    "$$I(Z;Y|X) \\geq \\sum_{i=1}^m \\mathbb{E}_{Z \\sim \\pi_\\theta(Z|x_i)}[\\log Q_\\rho(y_i|x_i, Z)]$$\n"
    "This follows from the data processing inequality applied to the conditional mutual information.",
    title="Variational lower bound for sufficiency term",
)

eps_smoothed_verifier_def = setting(
    "The $\\varepsilon$-smoothed verifier $\\tilde{Q}_\\rho(y|x,z)$ is defined as:\n"
    "$$\\tilde{Q}_\\rho(y|x,z) := \\varepsilon + (1-\\varepsilon) \\cdot \\mathbf{1}(\\hat{y}(x,z)=y)$$\n"
    "where $\\varepsilon > 0$ is a small constant and $\\hat{y}(x,z)$ is the predicted answer "
    "extracted from the reasoning trace z. This smoothing avoids $\\log(0)$ in the reward.",
    title="Epsilon-smoothed verifier definition",
)

information_cost_def = setting(
    "The information cost $C(Z)$ of a reasoning trace Z is defined as:\n"
    "$$C(Z) := \\sum_{t=1}^{|Z|} -\\log Q_\\phi(z_t | z_{<t})$$\n"
    "where $Q_\\phi$ is a frozen base language model prior (not instruction-finetuned). "
    "This quantity equals the cross-entropy of Z under the prior model, i.e., the surprisal "
    "of each token given the preceding context.",
    title="Information cost as token surprisal definition",
)

combined_reward_def = setting(
    "The combined reward function for CIB-based RL training is:\n"
    "$$R(X,Y,Z) := r_{\\text{acc}}(X,Y,Z) + \\beta \\cdot r_{\\text{min}}(X,Z)$$\n"
    "where $r_{\\text{acc}}(X,Y,Z) := \\mathbf{1}(\\hat{y}(x,z)=y)$ is the binary accuracy reward "
    "and $r_{\\text{min}}(X,Z) := \\sum_t \\log Q_\\phi(z_t | z_{<t})$ is the minimality reward "
    "(negative information cost). $\\beta$ controls the compression-accuracy trade-off.",
    title="Combined CIB reward function definition",
)

# --- Core theoretical claims ---

attention_paradox = claim(
    "Standard Information Bottleneck (IB) assumes a Markov chain structure Y ↔ X ↔ Z, where the "
    "compressed representation Z mediates all information from input X to output Y. However, "
    "transformer decoder architectures violate this Markov assumption: via causal self-attention "
    "and the key-value cache, the answer generation directly attends to both the prompt X and "
    "reasoning trace Z simultaneously. This creates a collider structure (X,Z)→Y rather than the "
    "chain X→Z→Y. The authors term this inconsistency the 'Attention Paradox'.",
    title="Attention Paradox: transformers violate IB Markov assumption",
    background=[ib_markov_def, transformer_attention_def],
    metadata={"source_section": "Section 3"},
)

transformer_attention_violates_markov = claim(
    "Transformer decoder architectures use causal self-attention that allows the answer "
    "generation step to attend directly to both the input prompt X and the reasoning trace Z "
    "via the key-value cache. This means the Markov chain assumption Y↔X↔Z required by "
    "standard IB is violated: Y depends on (X,Z) jointly rather than on Z alone.",
    title="Transformer attention directly violates IB Markov assumption",
    background=[transformer_attention_def, ib_markov_def],
)

strat_attention_paradox = support(
    [transformer_attention_violates_markov],
    attention_paradox,
    reason=(
        "@transformer_attention_violates_markov establishes that transformer decoders condition "
        "Y on (X,Z) jointly — a collider structure — rather than on Z alone as required by the "
        "Markov chain Y↔X↔Z. This inconsistency between the IB assumption and the actual "
        "transformer architecture is precisely what the authors term the Attention Paradox: "
        "applying standard IB to transformer reasoning is theoretically misspecified."
    ),
    prior=0.92,
)

cib_resolves_paradox = claim(
    "The Conditional Information Bottleneck (CIB) framework resolves the Attention Paradox by "
    "treating the prompt X as side information always available to the answer generator. "
    "The CIB objective maximizes $I(Z;Y|X)$ (how much Z explains Y given X) while minimizing "
    "$I(X;Z)$ (how redundant Z is with X). This correctly accounts for the transformer's "
    "direct access to X during answer generation.",
    title="CIB resolves Attention Paradox by conditioning on X",
    background=[cib_objective_def],
    metadata={"source_section": "Section 3"},
)

strat_cib_resolves = deduction(
    [attention_paradox],
    cib_resolves_paradox,
    reason=(
        "Since the Attention Paradox (@attention_paradox) arises because transformers condition Y "
        "on (X,Z) jointly rather than on Z alone, the correct information-theoretic objective "
        "must condition on X. The CIB sufficiency term I(Z;Y|X) measures how much Z contributes "
        "to Y beyond what X alone provides, directly matching the collider structure (X,Z)→Y. "
        "The minimality term I(X;Z) penalizes Z for repeating information already in X, "
        "discouraging redundant reasoning steps."
    ),
    prior=0.95,
)

acc_reward_derivation = claim(
    "The CIB accuracy reward $r_{\\text{acc}}(X,Y,Z) = \\mathbf{1}(\\hat{y}(x,z)=y)$ is derived "
    "from the variational lower bound on $I(Z;Y|X)$ via an $\\varepsilon$-smoothed binary verifier "
    "$\\tilde{Q}_\\rho$. Maximizing the lower bound $\\sum_i \\mathbb{E}[\\log \\tilde{Q}_\\rho(y_i|x_i,Z)]$ "
    "is equivalent (up to constants) to maximizing the indicator $\\mathbf{1}(\\hat{y}=y)$.",
    title="Binary accuracy reward derived from variational sufficiency bound",
    background=[variational_sufficiency_def, eps_smoothed_verifier_def],
    metadata={"source_section": "Section 3"},
)

strat_acc_reward = support(
    [cib_resolves_paradox],
    acc_reward_derivation,
    reason=(
        "Given the CIB objective (@cib_resolves_paradox), the variational lower bound on "
        "$I(Z;Y|X)$ (see @variational_sufficiency_def) yields the bound "
        "$\\sum_i \\mathbb{E}[\\log Q_\\rho(y_i|x_i,Z)]$. Using the $\\varepsilon$-smoothed verifier "
        "(see @eps_smoothed_verifier_def) $\\tilde{Q}_\\rho = \\varepsilon + (1-\\varepsilon)\\mathbf{1}(\\hat{y}=y)$, "
        "taking the log and discarding additive constants that do not depend on $\\theta$ gives "
        "$r_{\\text{acc}} = \\mathbf{1}(\\hat{y}=y)$ as the practical reward signal. The $\\varepsilon$ "
        "smoothing ensures the log is always defined even for wrong answers."
    ),
    prior=0.97,
    background=[variational_sufficiency_def, eps_smoothed_verifier_def],
)

min_reward_derivation = claim(
    "The CIB minimality reward $r_{\\text{min}}(X,Z) = \\sum_t \\log Q_\\phi(z_t|z_{<t})$ is "
    "derived from the variational upper bound on $I(X;Z)$:\n"
    "$$I(X;Z) \\leq \\mathbb{E}_{X,Z}[-\\log Q_\\phi(Z)] - H(Z|X)$$\n"
    "Minimizing $I(X;Z)$ is upper-bounded by minimizing $\\mathbb{E}_{X,Z}[-\\log Q_\\phi(Z)]$, "
    "i.e., maximizing the log-likelihood of Z under the frozen base model prior $Q_\\phi$.",
    title="Semantic surprisal reward derived from variational minimality bound",
    background=[information_cost_def],
    metadata={"source_section": "Section 3"},
)

strat_min_reward = support(
    [cib_resolves_paradox],
    min_reward_derivation,
    reason=(
        "Given the CIB objective (@cib_resolves_paradox), the mutual information $I(X;Z)$ between "
        "prompt and trace can be upper bounded using a variational distribution $Q_\\phi$: "
        "$I(X;Z) \\leq \\mathbb{E}_{X,Z}[-\\log Q_\\phi(Z)] - H(Z|X)$. "
        "Since $H(Z|X)$ is not controlled by policy parameters, minimizing the upper bound is "
        "equivalent to minimizing $\\mathbb{E}[-\\log Q_\\phi(Z)]$, i.e., the average information "
        "cost $C(Z)$ (see @information_cost_def). "
        "This becomes the reward $r_{\\text{min}} = \\sum_t \\log Q_\\phi(z_t|z_{<t})$."
    ),
    prior=0.97,
    background=[information_cost_def],
)

semantic_cost_advantage = claim(
    "The semantic cost function $C(Z) = \\sum_t -\\log Q_\\phi(z_t|z_{<t})$ (token surprisal "
    "under a frozen base language model) assigns higher cost to task-specific, low-probability "
    "tokens and lower cost to generic, high-probability tokens. This distinguishes informative "
    "reasoning tokens from conversational filler, which uniform token-count penalties cannot do.",
    title="Semantic surprisal cost distinguishes informative from filler tokens",
    background=[information_cost_def, combined_reward_def],
    metadata={"source_section": "Section 3"},
)

strat_semantic_cost = support(
    [min_reward_derivation, budget_forcing_heuristic],
    semantic_cost_advantage,
    reason=(
        "The minimality reward (@min_reward_derivation) uses surprisal under a general base model "
        "$Q_\\phi$ (not fine-tuned for math). Common discourse patterns ('let me think step by step', "
        "repeated phrases) have high probability under $Q_\\phi$ (low surprisal, low cost), so they "
        "are penalized more aggressively. Rare mathematical derivations have low probability (high "
        "surprisal, high cost) but are kept if they contribute to correctness (balanced by "
        "$r_{\\text{acc}}$). By contrast, @budget_forcing_heuristic shows flat token penalties "
        "cannot make this distinction."
    ),
    prior=0.88,
)

rl_objective_formulation = claim(
    "The CIB framework yields a principled reinforcement learning training objective: "
    "maximize task reward while compressing completions under a prior over reasoning traces. "
    "Concretely, the policy $\\pi_\\theta$ is trained using GRPO [@Shao2024] with the combined "
    "reward $R(X,Y,Z) = r_{\\text{acc}}(X,Y,Z) + \\beta \\cdot r_{\\text{min}}(X,Z)$, "
    "where $\\beta$ is the compression trade-off hyperparameter.",
    title="CIB yields RL objective: maximize accuracy minus compression cost",
    background=[combined_reward_def, grpo_def],
    metadata={"source_section": "Section 3"},
)

strat_rl_objective = deduction(
    [acc_reward_derivation, min_reward_derivation],
    rl_objective_formulation,
    reason=(
        "Combining the variational lower bound on $I(Z;Y|X)$ maximized via @acc_reward_derivation "
        "and the variational upper bound on $I(X;Z)$ minimized via @min_reward_derivation yields "
        "the combined reward @combined_reward_def. This reward is then optimized with GRPO "
        "(a practical RL algorithm for LLMs). The trade-off $\\beta$ traverses the Pareto frontier "
        "between accuracy and compression."
    ),
    prior=0.96,
)
