"""Section 3: The SGS Algorithm"""

from gaia.lang import claim, setting, support, deduction

from .motivation import (
    setup_asymmetric_selfplay,
    setup_lean4_domain,
    setup_conjecturer_reward,
    guide_hypothesis,
    conjecturer_collapse_hypothesis,
)

# ── Settings ──────────────────────────────────────────────────────────────────

setup_sgs_roles = setting(
    "In Self-Guided Self-Play (SGS), a single language model takes on three distinct roles: "
    "(1) Solver πθ: attempts to solve both target and synthetic problems; "
    "(2) Conjecturer gϕ: generates synthetic problems conditioned on unsolved target problems; "
    "(3) Guide ρ: an LLM-based judge that evaluates synthetic problem quality. "
    "All three roles are initialized from the same base model.",
    title="SGS three-role architecture",
)

setup_dataset = setting(
    "SGS operates on a fixed dataset D = {x1, ..., xN} of hard problems with verifiable "
    "solutions. The goal is to solve as many problems in D as possible given a large compute "
    "budget. In the paper's experiments, D = D3k, a dataset of 3,323 formal math problems "
    "in Lean4.",
    title="Fixed target problem dataset",
)

setup_conjecturer_prompt = setting(
    "The Conjecturer is prompted with an unsolved target problem and asked to produce a related "
    "lemma or theorem in Lean4. The prompt instructs the Conjecturer to produce a statement "
    "that: (1) is conceptually related but simpler to solve than the target, (2) is not identical "
    "to the target, and (3) is not equivalent through variable renaming. The output must be a "
    "syntactically correct Lean4 theorem statement.",
    title="Conjecturer prompt structure",
)

setup_guide_rubric = setting(
    "The Guide scores each synthetic problem on two dimensions: (1) relevance — how well the "
    "synthetic problem relates to the unsolved target problem; (2) elegance — whether the "
    "problem is formulated clearly with a simple conclusion and no redundant premises. "
    "The Guide is a copy of the base model fine-tuned on 2,048 well-formatted examples "
    "generated by GPT-4.1 mini to ensure reliable output formatting (>99% well-formatted).",
    title="Guide scoring rubric: relevance and elegance",
)

setup_rsolve = setting(
    "The solve-rate reward Rsolve for a synthetic problem x̃ is defined as follows. "
    "Let s(x̃) = (1/k) Σ v(yᵢ_x̃) be the empirical solve rate across k Solver rollouts. "
    "Rsolve = 0 if s(x̃) = 0 (too difficult) or if s(x̃) is in the top 30% of solve rates "
    "within the current batch (too easy). For all other synthetic problems, "
    "Rsolve = 1 − s(x̃), thereby favoring harder problems within the solvable range.",
    title="Solve-rate reward Rsolve definition",
)

setup_rguide = setting(
    "The Guide reward Rguide = ρ(x, x̃) ∈ [0, 1] is produced by the Guide LLM, indicating "
    "how well the synthetic problem x̃ relates to the unsolved target x and how elegant a "
    "conjecture it is. The combined Conjecturer reward is Rsynth = Rsolve · Rguide, "
    "linearly normalized within its batch to [0, 1].",
    title="Guide reward Rguide and combined Conjecturer reward",
)

setup_solver_objective = setting(
    "The Solver is updated using the REINFORCE1/2 objective: a REINFORCE objective applied "
    "only to problems with empirical solve rate ≤ 0.5, promoting learning on hard problems. "
    "Because the reward is binary (correct/incorrect proof), this reduces to a simple "
    "log-likelihood objective over all correct rollouts for problems with solve rate ≤ 0.5.",
    title="REINFORCE1/2 Solver update objective",
)

setup_length_penalty = setting(
    "A length penalty is applied to all RL updates. Rollouts consuming between 80% and 100% "
    "of the context window (8192 tokens) receive a negative reward scaling linearly from 0 "
    "to −1. Additionally, proofs using the 'try' tactic receive zero reward, as this tactic "
    "can cause infinite loops.",
    title="Length penalty and tactic reward shaping",
)

# ── Claims ────────────────────────────────────────────────────────────────────

sgs_two_mechanisms = claim(
    "SGS uses two mechanisms to prevent Conjecturer degradation: (1) conditioning the "
    "Conjecturer on unsolved target problems, so synthetic problems are directed toward the "
    "learning frontier; (2) using the Guide to score synthetic problems on relevance and "
    "elegance, down-weighting problems that are superficially related to targets but messy, "
    "overly complex, or inelegant.",
    title="SGS two anti-collapse mechanisms",
)

strat_two_mechanisms_design = support(
    [guide_hypothesis, conjecturer_collapse_hypothesis],
    sgs_two_mechanisms,
    background=[setup_sgs_roles],
    reason=(
        "Since the Conjecturer collapses when rewarded only by pass rate (@conjecturer_collapse_hypothesis), "
        "two complementary interventions are needed. First, conditioning on unsolved targets "
        "(@setup_sgs_roles) directs the Conjecturer toward problems near the Solver's learning "
        "frontier. Second, because language models can assess subproblem usefulness (@guide_hypothesis), "
        "a Guide model can provide a quality signal that penalizes the degenerate, inelegant "
        "problems that arise from reward hacking. Together, these define the two anti-collapse "
        "mechanisms of SGS [@Bailey2026]."
    ),
    prior=0.87,
)

sgs_conjecturer_conditions_on_unsolved = claim(
    "In SGS, for each unsolved problem x in the current batch, the Conjecturer gϕ generates "
    "one synthetic problem x̃ ~ gϕ(·|x) conditioned on x. Only unsolved problems generate "
    "synthetic problems; solved problems do not. This conditioning ensures synthetic problems "
    "are directed toward the Solver's current learning frontier.",
    title="Conjecturer conditioning on unsolved problems",
)

sgs_guide_scores_quality = claim(
    "The Guide ρ evaluates each synthetic problem x̃ relative to its conditioning target x, "
    "producing a quality score Rguide = ρ(x, x̃) ∈ [0, 1]. This score is based on (1) how "
    "relevant x̃ is to x, and (2) how elegantly x̃ is formulated (simple conclusion, no "
    "redundant premises). A synthetic problem that is superficially related but messy or "
    "overly complex receives a low Guide score and is thus down-weighted in the Conjecturer update.",
    title="Guide scores synthetic problem quality",
)

sgs_combined_reward = claim(
    "The combined Conjecturer reward for a synthetic problem x̃ is Rsynth = Rsolve · Rguide. "
    "This multiplicative formulation ensures that a synthetic problem must be both appropriately "
    "difficult for the Solver (captured by Rsolve) and high quality according to the Guide "
    "(captured by Rguide) to receive high reward. Either factor being zero zeroes out the reward.",
    title="Combined Conjecturer reward Rsynth = Rsolve · Rguide",
)

strat_combined_reward = deduction(
    [sgs_guide_scores_quality, sgs_conjecturer_conditions_on_unsolved],
    sgs_combined_reward,
    background=[setup_rsolve, setup_rguide],
    reason=(
        "The combined reward follows directly from the definitions of Rsolve (@setup_rsolve) "
        "and Rguide (@setup_rguide): Rsynth = Rsolve · Rguide. The Guide scores quality "
        "(@sgs_guide_scores_quality) and conditioning on unsolved problems (@sgs_conjecturer_conditions_on_unsolved) "
        "together instantiate both components. The multiplicative structure is a deliberate "
        "design choice: both difficulty appropriateness and quality must be satisfied for non-zero "
        "reward [@Bailey2026]."
    ),
    prior=0.99,
)

guide_sft_prevents_format_errors = claim(
    "DeepSeek-Prover-V2-7B, when used as the Guide without fine-tuning, produces correctly "
    "formatted reviewer outputs only 54.7% of the time — an unacceptably high error rate for "
    "an untrained Guide component. After supervised fine-tuning (SFT) on 2,048 examples of "
    "well-formatted Guide outputs (generated by GPT-4.1 mini), the rate of correctly formatted "
    "Guide outputs rises to over 99%.",
    title="Guide SFT improves format compliance from 54.7% to >99%",
)
