"""Section 2: Experimental Setup — Datasets, Models, Algorithms, and Metrics"""

from gaia.lang import claim, setting, support, deduction
from .motivation import controlled_pretraining_setup

# ── Settings ────────────────────────────────────────────────────────────────

olmo_architecture = setting(
    "OLMo is an open decoder-only transformer. Two scales are used: "
    "150M parameters (hidden width 768, 12 layers) and 1B parameters (hidden width 2048, 16 layers). "
    "Both use SwiGLU activations and Rotary Positional Encoding (RoPE).",
    title="OLMo model architecture",
)

pretraining_corpus_definition = setting(
    "Document corpora used for pretraining: (1) FineMath-3+, a filtered web corpus of "
    "high-quality mathematical content; (2) Proof-Pile-2 (Algebraic-Stack subset), a "
    "corpus of formal and informal mathematical proofs. These provide broad mathematical "
    "background without a specific solution format.",
    title="Document corpora (FineMath, Proof-Pile)",
)

tinygsm_definition = setting(
    "TinyGSM is an instruction dataset of 12.3 million math problem-solution pairs generated "
    "by GPT-3.5. Solutions are predominantly in Python code format (code-style solutions). "
    "Each solution includes a Python function that computes the answer.",
    title="TinyGSM dataset definition",
)

openmathinstruct1_definition = setting(
    "OpenMathInstruct1 (OMI1) is an instruction dataset of 1.8 million math problem-solution "
    "pairs generated by Mixtral-8x7B. Solutions are predominantly in Python code format, "
    "similar to TinyGSM but at smaller scale and different generator model.",
    title="OpenMathInstruct1 dataset definition",
)

openmathinstruct2_definition = setting(
    "OpenMathInstruct2 (OMI2) is an instruction dataset of 14 million math problem-solution "
    "pairs generated by Llama3.1-405B. Solutions are in natural language (chain-of-thought) "
    "format rather than Python code.",
    title="OpenMathInstruct2 dataset definition",
)

rl_algorithms_definition = setting(
    "Three RL post-training algorithms are evaluated: "
    "(1) PPO (Proximal Policy Optimization): clips the policy gradient ratio to stabilise training. "
    "(2) GRPO (Group Relative Policy Optimization): uses group-relative baseline for reward normalisation. "
    "(3) Expert Iteration (EI): iteratively filters and fine-tunes on correct generations. "
    "All use a binary reward: +1 for correct final answer, 0 otherwise. "
    "RL fine-tuning is performed on the GSM8K training set (grade-school math word problems).",
    title="RL algorithms and reward definition",
)

evaluation_metrics_definition = setting(
    "Three evaluation metrics are reported: "
    "(1) Pass@1: accuracy of a single greedy decoding. "
    "(2) Pass@64: probability that at least one of 64 sampled generations is correct (measures diversity + capability). "
    "(3) Majority@64: accuracy when taking the most-frequent answer across 64 samples (measures consensus reliability). "
    "Benchmarks: GSM8K (easy), MATH-500 (medium), AIME (hard).",
    title="Evaluation metrics and benchmarks",
)

format_tracking_method = setting(
    "Format tracking identifies the pretraining source of each generated response by detecting "
    "distinctive structural markers: TinyGSM/OMI1 responses contain Python `def solution():` "
    "function headers; OMI2 responses use natural language reasoning paragraphs. "
    "This allows monitoring the fraction of outputs attributable to each pretraining distribution "
    "throughout RL training.",
    title="Format tracking methodology",
)

# ── Claims ───────────────────────────────────────────────────────────────────

format_distinctiveness = claim(
    "The three instruction datasets (TinyGSM, OpenMathInstruct1, OpenMathInstruct2) have "
    "sufficiently distinctive output formats—code vs. natural language—that individual "
    "generated responses can be reliably attributed to one source distribution. "
    "This distinctiveness enables format-proportion tracking across RL training.",
    title="Format distinctiveness enables tracking",
    metadata={"source_section": "Section 2 / Methods"},
)

code_vs_nl_gap = claim(
    "The structural gap between Python code format (syntactically rigid function templates, "
    "machine-checkable) and natural language prose format (stylistically variable paragraphs) "
    "is large enough that automated classification of individual responses by source "
    "distribution is reliable. TinyGSM and OMI1 responses contain `def solution():` "
    "headers; OMI2 responses use paragraph-style reasoning.",
    title="Code vs. natural-language structural gap enables reliable classification",
    metadata={"source_section": "Section 2 / Methods"},
)

strat_format_distinctiveness = support(
    [code_vs_nl_gap],
    format_distinctiveness,
    reason=(
        "Because @code_vs_nl_gap establishes that Python function templates and natural "
        "language prose are structurally distinct (syntactic markers in code vs. free-form "
        "prose), automated classification of each response to TinyGSM/OMI1 (code) or "
        "OMI2 (NL) is reliable. @format_tracking_method operationalises this via `def solution():` "
        "detection. Therefore @format_distinctiveness holds."
    ),
    prior=0.88,
    background=[format_tracking_method, tinygsm_definition, openmathinstruct1_definition, openmathinstruct2_definition],
)

controlled_ablation_design = claim(
    "By pretraining multiple model variants on different mixtures of the same documented "
    "datasets (document corpora + varying combinations of TinyGSM, OMI1, OMI2) and then "
    "applying identical RL fine-tuning, the study creates controlled comparisons where "
    "the only variable is pretraining data composition.",
    title="Controlled ablation design",
    metadata={"source_section": "Section 2 / Methods"},
)

strat_ablation_design = deduction(
    [format_distinctiveness],
    controlled_ablation_design,
    reason=(
        "Given @controlled_pretraining_setup (all training done from scratch on documented "
        "open data — see background), and @format_distinctiveness (outputs can be traced back "
        "to source distributions), the experimental design logically constitutes a controlled "
        "ablation: any post-RL distributional shift is attributable to the pretraining mixture, "
        "not to unknown factors."
    ),
    prior=0.97,
    background=[controlled_pretraining_setup, olmo_architecture, rl_algorithms_definition],
)

__all__ = ["controlled_ablation_design", "format_distinctiveness"]
