"""Section 4.1: Environment-Aware Verifier Architecture"""

from gaia.lang import claim, setting, support, deduction
from .motivation import (
    setup_prm, setup_data_analysis,
    claim_silent_errors, claim_grounding_errors,
)

# ── Settings: DataPRM design foundations ──────────────────────────────────────

setup_react_prm = setting(
    "DataPRM adopts the same ReAct paradigm as the data analysis agent itself. "
    "Given a trajectory $h_t$ of the policy model and its current step $\\tau_t = "
    "(z_t, a_t, o_t)$ at time $t$, the input context is $h_{t,0}^{prm} = h_t "
    "\\oplus \\tau_t$. DataPRM then engages in a multi-step internal verification "
    "loop, generating verification tuples $\\kappa_{t,k} = (\\hat{z}_k, \\hat{a}_k, "
    "\\hat{o}_k)$ at each internal step $k$, producing a final score $r_t$ and "
    "rationale $c_t$.",
    title="DataPRM ReAct verification paradigm"
)

setup_ternary_reward = setting(
    "DataPRM uses a ternary reward space $r_t \\in \\{0, 0.5, 1\\}$ instead of "
    "binary $\\{0, 1\\}$: Strictly Correct ($r_t = 1.0$) = logically sound and "
    "advances solution; Irrecoverable Error ($r_t = 0.0$) = fundamental logic "
    "flaws or hallucinations steering trajectory to dead end; Correctable Error "
    "($r_t = 0.5$) = minor error (syntax, file path) that triggers environment "
    "feedback allowing correction.",
    title="Ternary reward strategy"
)

setup_tool_augmented = setting(
    "DataPRM is equipped with two tools: query_document and query_image. These "
    "allow the verifier to query related questions about data files or visualization "
    "images through function calls, bridging internal reasoning with external "
    "perception capabilities.",
    title="Tool-augmented verification"
)

setup_verification_history = setting(
    "The feedback tuple $(r_t, c_t)$ generated by DataPRM is explicitly appended "
    "to the context for the next step's verification. Given historical verification "
    "results $f_t = (r_0, c_0, r_1, c_1, \\ldots, r_{t-1}, c_{t-1})$, the input "
    "redefines as $h_{t,0}^{prm} = h_t \\oplus f_t \\oplus \\tau_t$, ensuring "
    "consistency and continuity of evaluation across steps.",
    title="Verification history propagation"
)

# ── Claims: architecture results ──────────────────────────────────────────────

claim_env_interaction_critical = claim(
    "Environment interaction is critical for process verification in data analysis. "
    "Ablation shows that adding code execution feedback (Single-turn Code w/ Env) "
    "improves over CoT baseline from 35.71% to 36.77% on Hard tasks at N=16. "
    "Multi-turn interaction alone provides marginal gains, but combined with "
    "environment it significantly boosts performance.",
    title="Environment interaction is critical for verification",
    metadata={"source_table": "artifacts/2604.24198.pdf, Table 3"}
)

claim_ternary_reward_benefit = claim(
    "The reflection-aware ternary reward strategy provides additional improvement "
    "beyond environment interaction. Full DataPRM (Env + Multi + Refl) achieves "
    "37.57% on Hard tasks at N=16, compared to 36.77% for Multi-turn Code w/ Env "
    "without ternary rewards. Fine-grained scoring of exploratory steps helps "
    "select correct trajectories.",
    title="Ternary reward improves trajectory selection",
    metadata={"source_table": "artifacts/2604.24198.pdf, Table 3"}
)

claim_prm_mirrors_agent = claim(
    "Effective verification in data analysis requires the PRM to have as many "
    "contextual interaction capabilities as the solution generation agent itself. "
    "This is the design principle behind DataPRM's ReAct-based architecture: the "
    "verifier mirrors the agent's capability to execute code, read documents, and "
    "inspect visualizations.",
    title="Verifier should mirror agent capabilities"
)

# ── Connect claims ────────────────────────────────────────────────────────────

strat_env_critical = support(
    [claim_silent_errors],
    claim_env_interaction_critical,
    reason=(
        "Silent errors (@claim_silent_errors) cannot be detected by text-only "
        "reasoning — the PRM must execute the code and inspect outputs to verify "
        "semantic correctness. DataPRM's ReAct paradigm (@setup_react_prm) enables "
        "this by allowing the verifier to run code in the environment, directly "
        "addressing the silent error blind spot."
    ),
    prior=0.90,
    background=[setup_react_prm],
)

strat_ternary_benefit = support(
    [claim_grounding_errors],
    claim_ternary_reward_benefit,
    reason=(
        "Grounding errors (@claim_grounding_errors) are correctable — penalizing "
        "them suppresses necessary exploration. The ternary reward (@setup_ternary_reward) "
        "distinguishes these from irrecoverable errors by assigning r=0.5 to "
        "correctable steps, allowing the agent to learn 'error → continue exploring' "
        "rather than 'error → abandon trajectory'."
    ),
    prior=0.88,
    background=[setup_ternary_reward],
)

strat_prm_mirrors = deduction(
    [claim_silent_errors, claim_grounding_errors],
    claim_prm_mirrors_agent,
    reason=(
        "Silent errors require execution capability to detect (@claim_silent_errors). "
        "Grounding errors require environment interaction to distinguish from "
        "irrecoverable errors (@claim_grounding_errors). Both requirements imply "
        "the verifier needs the same interaction capabilities as the agent."
    ),
    prior=0.95,
)
